/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalprograii;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author dcasc
 */
public class Login extends javax.swing.JFrame {
 ArrayList<Usuarios> usuarios = new ArrayList();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        usuariosPorDefecto();
    }
     private void usuariosPorDefecto(){
         Usuarios Diego = new Usuarios("DiegoAdmin","DCA","Casco","admin",new Date(),"Administador");
         usuarios.add(Diego);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JT_Usuario = new javax.swing.JTextField();
        jb_Login = new javax.swing.JButton();
        Jb_registrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JF_Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Administrador de Empresa");

        jb_Login.setText("Login");
        jb_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LoginActionPerformed(evt);
            }
        });

        Jb_registrar.setText("Registrar");
        Jb_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb_registrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Contasena");

        jLabel3.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JT_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                        .addComponent(JF_Password))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_Login)
                        .addGap(207, 207, 207)
                        .addComponent(Jb_registrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JT_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(JF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Login)
                    .addComponent(Jb_registrar))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LoginActionPerformed
        // TODO add your handling code here:
        boolean entra = false;
        for(Usuarios usuario : usuarios){
            if(usuario.getUsuario().equals(JT_Usuario.getText())&& usuario.getContrasena().equals(JF_Password.getText())&& usuario.getTipocuenta().equals("Administador")){
                Admin a = new Admin();
                a.setVisible(true);
                JOptionPane.showMessageDialog(null, "Bienvenido " + usuario.getUsuario());
                entra = true;
                this.dispose();
            }if(usuario.getUsuario().equals(JT_Usuario.getText())&& usuario.getContrasena().equals(JF_Password.getText())&& usuario.getTipocuenta().equals("Gerente")){
                Gerente g = new Gerente();
                g.setVisible(true);
                JOptionPane.showMessageDialog(null, "Bienvenido " + usuario.getUsuario());
                entra = true;
                this.dispose();
            }if(usuario.getUsuario().equals(JT_Usuario.getText())&& usuario.getContrasena().equals(JF_Password.getText())&& usuario.getTipocuenta().equals("Empleado")){
                Empleado e = new Empleado();
                e.setVisible(true);
                JOptionPane.showMessageDialog(null, "Bienvenido " + usuario.getUsuario());
                entra = true;
                this.dispose();
            }if(usuario.getUsuario().equals(JT_Usuario.getText())&& usuario.getContrasena().equals(JF_Password.getText())&& usuario.getTipocuenta().equals("Cliente")){
                Clientemenu c = new Clientemenu();
                c.setVisible(true);
                JOptionPane.showMessageDialog(null, "Bienvenido " + usuario.getUsuario());
                entra = true;
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_jb_LoginActionPerformed

    private void Jb_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb_registrarActionPerformed
        // TODO add your handling code here:
        Registro r = new Registro();
        r.setVisible(true);
        r.usuarios = usuarios; 
    }//GEN-LAST:event_Jb_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JF_Password;
    private javax.swing.JTextField JT_Usuario;
    private javax.swing.JButton Jb_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb_Login;
    // End of variables declaration//GEN-END:variables
}
